name: Deploy MultiK8S
on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t krumk/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true krumk/react-test npm test


  apply:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: cicdudemy
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: europe-central2-a

      - name: Dockerize
        run: |- 
          pwd
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t krumk/multi-client-k8s -f ./client/Dockerfile ./client
          docker build -t krumk/multi-server-k8s -f ./server/Dockerfile ./server
          docker build -t krumk/multi-worker-k8s -f ./worker/Dockerfile ./worker
      
      - name: Push
        run: |- 
          docker push krumk/multi-client-k8s:latest
          docker push krumk/multi-server-k8s:latest
          docker push krumk/multi-worker-k8s:latest

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/api-deployment server=krumk/multi-server-k8s
          kubectl set image deployments/client-deployment client=krumk/multi-client-k8s
          kubectl set image deployments/worker-deployment worker=krumk/multi-worker-k8s
