name: Deploy Frontend
on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t krumk/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true krumk/react-test npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t krumk/mutli-client  ./client
      - run: docker build -t krumk/mutli-nginx  ./nginx
      - run: docker build -t krumk/mutli-server  ./server
      - run: docker build -t krumk/mutli-worker  ./worker
