name: Deploy Frontend
on:
  push:
    branches:
      - main
  
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     - run: docker build -t krumk/react-test -f ./client/Dockerfile.dev ./client
  #     - run: docker run -e CI=true krumk/react-test npm test

  # dockerize:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2

  #     - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     - run: docker build -t krumk/multi-client  ./client
  #     - run: docker build -t krumk/multi-nginx  ./nginx
  #     - run: docker build -t krumk/multi-server  ./server
  #     - run: docker build -t krumk/multi-worker  ./worker
  #     - run: docker push krumk/multi-client
  #     - run: docker push krumk/multi-nginx
  #     - run: docker push krumk/multi-server
  #     - run: docker push krumk/multi-worker
  
  deploy:
    runs-on: ubuntu-latest
    # needs: dockerize
    steps:
        - name: Generate deployment package
          run: zip -r deploy.zip * -x "**node_modules**"
             
        - name: Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v18
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: multi-docker
            environment_name: Multidocker-env
            existing_bucket_name: elasticbeanstalk-eu-central-1-192858519801
            region: eu-central-1
            version_label: ${{ github.sha }}
            deployment_package: deploy.zip
